version: '3'

networks:
  backend:
    driver: "bridge"

services:
  spring:
    container_name: spring-api
    build: .
    ports:
        - "8080:8080"
    networks:
        - backend 
    links:
        - elasticsearch
    command: >
        sh -c "sleep 20 && java -jar /spring/app.jar"

  elasticsearch: # Elasticsearch Instance
    container_name: spring-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
    networks:
      - backend 

volumes: # Define seperate volume for Elasticsearch data
  esdata:
